site_name: Fief
site_url: https://docs.fief.dev

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/fief-logo-white.svg
  favicon: assets/images/favicon.svg
  font:
    text: Inter
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotate

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - tables
  - def_list

extra:
  header_links:
    - title: About
      href: https://www.fief.dev
    - title: Join the beta
      href: https://www.fief.dev

extra_css:
  - assets/stylesheets/extra.css

nav:
  - index.md
  - 'Getting started':
    - getting-started/introduction.md
    - getting-started/workspace.md
    - getting-started/admin-dashboard.md
    - getting-started/tenants.md
    - getting-started/clients.md
    - getting-started/users.md
    - getting-started/api-keys.md
  - 'Integrate':
    - 'Python':
      - integrate/python/index.md
      - integrate/python/fastapi.md
      - integrate/python/flask.md
  - 'Going further':
    - going-further/byod.md
    - going-further/id-token-encryption.md
  - 'Self-hosting':
    - self-hosting/quickstart.md
    - self-hosting/setup-database.md
    - self-hosting/setup-email-provider.md
    - self-hosting/environment-variables.md
  - Miscellaneous:
    - miscellaneous/resources.md
