site_name: Fief
site_url: https://docs.fief.dev

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/fief-logo-white.svg
  favicon: assets/images/favicon.svg
  font:
    text: Inter
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate

plugins:
  - search
  - tags

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - tables
  - def_list

extra:
  analytics:
    provider: posthog
  header_links:
    - title: About
      href: https://www.fief.dev
    - title: Discussions
      href: https://github.com/orgs/fief-dev/discussions
    - title: Join the beta
      href: https://fief.fief.dev/admin/api/auth/login?screen=register

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/fernet.js

watch:
- examples
- reusables

nav:
  - index.md
  - 'Getting started':
    - getting-started/introduction.md
    - getting-started/workspace.md
    - getting-started/admin-dashboard.md
    - getting-started/tenants.md
    - getting-started/clients.md
    - getting-started/oauth-providers.md
    - getting-started/users.md
    - getting-started/user-fields.md
    - getting-started/access-control.md
    - getting-started/api-keys.md
    - getting-started/oauth2.md
  - 'Integrate':
    - 'Python':
      - 'General': integrate/python/index.md
      - integrate/python/fastapi.md
      - integrate/python/flask.md
      - 'Reference ↗️': https://fief-dev.github.io/fief-python/
    - 'JavaScript':
      - 'General': integrate/javascript/index.md
      - integrate/javascript/browser.md
      - integrate/javascript/react.md
  - 'Going further':
    - going-further/byod.md
    - going-further/pkce.md
    - going-further/id-token-encryption.md
    - going-further/oauth-provider-token.md
  - 'Self-hosting':
    - self-hosting/quickstart.md
    - 'Production deployment':
      - self-hosting/deployment/docker-compose.md
      - self-hosting/deployment/render.md
      - self-hosting/deployment/setup-database.md
      - self-hosting/deployment/setup-email-provider.md
    - self-hosting/environment-variables.md
  - Miscellaneous:
    - miscellaneous/resources.md
