contact_links:
  - name: 🤔 I have a question
    url: https://github.com/fief-dev/fief/discussions/new?category=q-a
    about: If you have any question about Fief that's not clearly an error, please open a discussion first.
